database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  name: "wazuh_db"

wazuh:
  url: "http://localhost:55000"
  username: "wazuh"
  password: "wazuh"

app:
  host: "0.0.0.0"
  port: 8080
  sync_interval: 300
